finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static  



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('finches/', views.finches_index),
  path('finches/<int:finch_id>/', views.finches_show, name='finches_show'),
  path('finches/create/', views.FinchCreate.as_view(), name='finches_create'),
  path('finches/<int:pk>/update/', views.FinchUpdate.as_view(), name='finches_update'),
  path('finches/<int:pk>/delete/', views.FinchDelete.as_view(), name='finches_delete'),
  path('finches/<int:finch_id>/add_feeding/', views.add_feeding, name='add_feeding'),
]

main_app/models.py
from django.db import models
from django.contrib import admin
from django import forms  

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)
class Finch(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    age = models.IntegerField()
    finch_image = models.ImageField(null=True, blank=True,upload_to='images/') 
    def __str__(self):
        return self.name
    
class Feeding(models.Model):
    date = models.DateField()
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
        )
    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

admin.site.register(Finch)
admin.site.register(Feeding)

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Finch
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .forms import FeedingForm

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def finches_index(request):
        finches = Finch.objects.all()
        return render(request, 'finches/index.html', { 'finches':finches })

def finches_show(request, finch_id):
        finch = Finch.objects.get(id=finch_id)
        feeding_form = FeedingForm()
        return render(request, 'finches/show.html', {'finch': finch,'feeding_form': feeding_form})
      
def add_feeding(request, finch_id):
  # create a ModelForm instance using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.finch_id = finch_id
    new_feeding.save()
  return redirect('finches_show', finch_id=finch_id)
        
class FinchCreate(CreateView):
  model = Finch
  fields = '__all__'
  success_url = '/finches'
  
class FinchUpdate(UpdateView):
  model = Finch
  # Let's disallow the renaming of a cat by excluding the name field!
  fields = '__all__'
  success_url = '/finches'


class FinchDelete(DeleteView):
  model = Finch
  success_url = '/finches/'
  

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Finch Collector🐦</h1>

<p class="flow-text #e0f2f1 teal lighten-5" align="justify">The true finches are small to medium-sized passerine birds in the family Fringillidae. Finches have stout conical bills adapted for eating seeds and nuts and often have colourful plumage. They occupy a great range of habitats where they are usually resident and do not migrate. They have a worldwide distribution except for Australia and the polar regions. The family Fringillidae contains more than two hundred species divided into fifty genera. It includes species known as siskins, canaries, redpolls, serins, grosbeaks and euphonias.

    Many birds in other families are also commonly called "finches". These groups include the estrildid finches (Estrildidae) of the Old World tropics and Australia; some members of the Old World bunting family (Emberizidae) and the New World sparrow family (Passerellidae); and the Darwin's finches of the Galapagos islands, now considered members of the tanager family (Thraupidae).[1]
    
    Finches and canaries were used in the UK, US and Canada in the coal mining industry to detect carbon monoxide from the eighteenth to twentieth century. This practice ceased in the UK in 1986.[2]</p>


{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Finch Collector</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="logo"><img src="{% static 'finchlogo.png' %}" /></a></li>
        </ul>
        <ul class="right">
          <li><a href="/about">About</a></li>
          <li><a href="/finches">View All My Finches</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    © {% now "Y" %} , Made with 
    <i class="fa fa-heart heart"></i> by SE --&gt; FMJS</footer>
</body>
</html>

main_app/templates/finches/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch List🕊️</h1>


<div class="right-align">
  <a href="/finches/create" class="waves-effect waves-light btn-large">Add a New Finch</a>
</div>


{% for finch in finches %}
{% comment %} <a href="/finches/{{finch.id}}"> //using name attri below  {% endcomment %}
  <a href= "{% url 'finches_show' finch.id %}">
  <div class="card hoverable">
    <div class="card-content">
      <div class="row center-align">
        <div class="grid-example col s12">
          <div class="card">
            <div class="card-image">
              {% if finch.finch_image %}

              <img src="{{ finch.finch_image.url}}">

              {% endif %}

            </div>
          </div>
        </div>
      </div>
      <span class="card-title">{{ finch.name }}</span>
      <p>Breed: {{ finch.breed }}</p>
      <p>Description: {{ finch.description }}</p>
      {% if finch.age > 0 %}
        <p>Age: {{ finch.age }}</p>
      {% else %}
        <p>Age: Newborn</p>
      {% endif %}
    </div>
  </div>
{% endfor %}
{% endblock %}

main_app/templates/finches/show.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch Collector</h1>

<div class="row">
  <div class="col s12">

    <div class="card hoverable">
    
      <div class="row center-align">
        <span class="card-title">Name:{{ finch.name }}</span>
        <p> Breed: {{ finch.breed }}</p>
        <p> Description: {{ finch.description }}</p>
        <p> Age: {{ finch.age }}</p>
      <div class="card-action">
        <a class="waves-effect waves-light btn-large" href="{% url 'finches_update' finch.id %}">Edit</a>
        <a class="waves-effect waves-light btn-large red" href="{% url 'finches_delete' finch.id %}">Delete</a>
      </div>
    </div>  
  
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' finch.id %}" method="post">
      {% csrf_token %}
    {{ feeding_form.as_p }}
    <input type="submit" class="btn" value="Add Feeding">
  </form>
</div>


  <div class="col s6">
    
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in finch.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>  
  
  </div>
</div>
      </div>
      
    </div>
    <script>
      var dateEl = document.getElementById('id_date');
      M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
      });

      var selectEl = document.getElementById('id_meal');
      M.FormSelect.init(selectEl);
    </script>
  </body>
</html>
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Welcome to Finch Collector Home Page🐦</h1>

{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Finch</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input class="waves-effect waves-light btn-large red" type="submit" value="Yes - Delete!" class="btn">
    <a class="waves-effect waves-light btn-large" href="{% url 'finches_show' finch.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Finch</h1>
  {% endif %}
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <div class="section">
      {% if object %}
      <input class="waves-effect waves-light btn-large" type="submit" value="Update">
      {% else %}
      <input class="waves-effect waves-light btn-large" type="submit" value="Add">
      {% endif %}
    </div>
  </form>
{% endblock %}